### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the Logistic Regression Lessons

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/1vis2e2aYid986w58hes8KTPxKcZFmFCW
     
2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project78** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement

Nowadays everyone possesses one or more email accounts for digital communication. You may have observed that your mailbox classifies your relevant emails as primary emails and other irrelevant emails as spam. 

**Spam** emails are junk emails or unrequired emails. They may consist of advertisements, updated, and unwanted messages which are sent to the receivers without their permission. Hence, spam detection is one of the important problem statement in email and messaging servicing. 

In this project, you will create a model to classify the emails as **spam** or **not spam** using Logistic Regression.

---

### List of Activities

**Activity 1:** Analysing the Dataset

**Activity 2:** Train-Test Split

**Activity 3:** Normalisation of the Features

**Activity 4:** Logistic Regression - Model Training

**Activity 5:** Logistic Regression - Model Prediction and Evaluation

---

 
#### Activity 1:  Analysing the Dataset
 
Create a Pandas DataFrame for **Spambase** dataset using the below link. This dataset consists of the following 58 columns. Most of the columns represent frequencies of a particular word or character in the email:
 
 
|Column #|Attribute|Description|
|-|-|-|
|0 - 47|word_freq_WORD|The first 48 columns are the percentage|
|||of the frequencies of the particular word one column each|
||||
|48 - 53|word_freq_CHAR|The next 6 columns are the percentage of the frequencies of the|
|||particular special character like semi-colon (;), exclamation (!) one column each|
||||
|54|capital_run_length_average|average length of uninterrupted sequences of capital letters|
||||
|55|capital_run_length_longest|length of longest uninterrupted sequence of capital letters|
||||
|56|capital_run_length_total|sum of the length of uninterrupted sequences of capital letters|
||||
|57|email_type|denotes whether the email is spam (1) or not (0)|
 
 
 
 -  **Dataset Link:** https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/spambase.csv
   
- **Source:** UCI Library https://archive.ics.uci.edu/ml/datasets/Spambase
 
 
 
 
 
 
Print the first five rows of the dataset. Check for null values and treat them accordingly (if any).

In [3]:
# Import modules
import pandas as pd 
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt 
# Load the dataset
df = pd.read_csv('https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/spambase.csv',header=None)
# Print the first five rows of the DataFrame
df.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

Rename the last column of the DataFrame as target.

In [4]:
# Rename the last column as 'target'
df.rename(columns={57:'Target'},inplace = True)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,Target
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

Print the information of the DataFrame to verify the above update.

In [5]:
# Print the dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4601 non-null   float64
 1   1       4601 non-null   float64
 2   2       4601 non-null   float64
 3   3       4601 non-null   float64
 4   4       4601 non-null   float64
 5   5       4601 non-null   float64
 6   6       4601 non-null   float64
 7   7       4601 non-null   float64
 8   8       4601 non-null   float64
 9   9       4601 non-null   float64
 10  10      4601 non-null   float64
 11  11      4601 non-null   float64
 12  12      4601 non-null   float64
 13  13      4601 non-null   float64
 14  14      4601 non-null   float64
 15  15      4601 non-null   float64
 16  16      4601 non-null   float64
 17  17      4601 non-null   float64
 18  18      4601 non-null   float64
 19  19      4601 non-null   float64
 20  20      4601 non-null   float64
 21  21      4601 non-null   float64
 22  22      4601 non-null   float64
 23  23      4601 non-null   float64
 24  24      4601 non-null   float64
 25  25      4601 non-null   float64
 26  26      4601 non-null   float64
 27  27      4601 non-null   float64
 28  28      4601 non-null   float64
 29  29      4601 non-null   float64
 30  30      4601 non-null   float64
 31  31      4601 non-null   float64
 32  32      4601 non-null   float64
 33  33      4601 non-null   float64
 34  34      4601 non-null   float64
 35  35      4601 non-null   float64
 36  36      4601 non-null   float64
 37  37      4601 non-null   float64
 38  38      4601 non-null   float64
 39  39      4601 non-null   float64
 40  40      4601 non-null   float64
 41  41      4601 non-null   float64
 42  42      4601 non-null   float64
 43  43      4601 non-null   float64
 44  44      4601 non-null   float64
 45  45      4601 non-null   float64
 46  46      4601 non-null   float64
 47  47      4601 non-null   float64
 48  48      4601 non-null   float64
 49  49      4601 non-null   float64
 50  50      4601 non-null   float64
 51  51      4601 non-null   float64
 52  52      4601 non-null   float64
 53  53      4601 non-null   float64
 54  54      4601 non-null   float64
 55  55      4601 non-null   int64
 56  56      4601 non-null   int64
 57  Target  4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

**Q:** Are there any missing values?

**A:**

---

#### Activity 2: Train-Test Split

You have to determine the effect of all the features on the 'target' variable. Thus, every column other than the `target` is the feature variable and `target` column is the target variable. 

**Steps:**

1. Create a list of all the features.

2. Split the "DataFrame" into features and target arrays using the features list.

3. Split the dataset into a training set and test set such that the training set contains 70% of the instances and the remaining instances will become the test set.

4. Reshape the target variable arrays into two-dimensional arrays by using `reshape(-1, 1)` function of the `numpy` module.

In [6]:
# Split the DataFrame into the train and test sets.
from sklearn.model_selection import train_test_split
col = list(df.columns)
col.pop()
x = df[col]
y = df['Target']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)
y_train = np.array(y_train).reshape(-1,1)
y_test = np.array(y_test).reshape(-1,1)

----

#### Activity 3: Normalisation of the Features
 
Get a descriptive analysis of the feature set and decide whether any normalisation is needed.

Describe the features for training data.

In [7]:
# Get the descriptive statistics for 'X_train'.
x_train.describe()

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
count,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,...,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000
mean,0.103031,0.198935,0.282693,0.062537,0.304134,0.091214,0.110612,0.104239,0.086410,0.234078,...,0.033134,0.037047,0.143244,0.017205,0.265803,0.073327,0.044412,5.186044,53.472360,279.445031
std,0.306817,1.240552,0.513786,1.337688,0.678832,0.265021,0.372645,0.413198,0.264451,0.639231,...,0.286595,0.232028,0.297126,0.099822,0.891430,0.215402,0.364088,32.834895,219.287284,579.628956
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.577750,6.000000,32.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.066000,0.000000,0.000000,0.000000,0.000000,2.270500,14.000000,92.000000
75%,0.000000,0.000000,0.412500,0.000000,0.360000,0.000000,0.000000,0.000000,0.000000,0.130000,...,0.000000,0.000000,0.188250,0.000000,0.301000,0.048000,0.000000,3.716000,42.000000,262.000000
max,4.540000,14.280000,5.100000,42.730000,10.000000,5.880000,7.270000,11.110000,3.330000,18.180000,...,10.000000,4.187000,9.752000,2.777000,32.478000,5.300000,13.129000,1102.500000,9989.000000,10062.000000

Describe the features for the testing data.

In [8]:
# Get the descriptive statistics for 'X_test'.
x_test.describe()

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
count,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,...,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000
mean,0.108103,0.245844,0.275909,0.072158,0.331086,0.106828,0.122592,0.107755,0.098595,0.251854,...,0.028921,0.042137,0.129206,0.016442,0.276691,0.081602,0.043833,5.204272,49.142650,292.252715
std,0.302007,1.400213,0.481055,1.521217,0.657398,0.293135,0.432133,0.371393,0.309066,0.657522,...,0.283801,0.268321,0.193832,0.129022,0.603364,0.305368,0.552484,29.000058,120.115201,664.623902
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.605000,7.000000,40.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.061000,0.000000,0.021000,0.000000,0.000000,2.285000,15.000000,106.000000
75%,0.000000,0.000000,0.430000,0.000000,0.440000,0.000000,0.000000,0.000000,0.000000,0.210000,...,0.000000,0.000000,0.186000,0.000000,0.349000,0.058000,0.000000,3.700000,45.000000,274.000000
max,4.000000,14.280000,4.340000,42.810000,9.090000,3.570000,7.270000,4.230000,5.260000,11.110000,...,8.330000,4.385000,1.932000,4.081000,8.333000,6.003000,19.829000,667.000000,1333.000000,15841.000000

**Q:** Does the data needs normalisation? Why?

**A:**


If the answer to the above question is **yes**, Normalise the data by calculating their $Z$-scores (or standard scaler) in the following code sections.

Define the Standard Normalisation function.

In [9]:
# Define the 'standard_scalar()' function for calculating Z-scores
def standard_scalar(s):
  return (s-s.mean())/s.std()

**Hint** 
$Z$-score for each value can be calculated by the following expression:

$$Z = \frac{X - \mu}{\sigma}$$

Where,


- $X$ is an observation 

- $\mu$ is the population mean

- $\sigma$ is the population standard deviation

Apply the normalisation function to the features of the training data.

In [10]:
# Apply the 'standard_scalar()' on X_train using apply() function and get the descriptive statistics of the normalised X_train
norm_x_train = x_train.apply(standard_scalar,axis=1)
norm_x_train.describe()

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
count,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,...,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000,3220.000000
mean,-0.170615,-0.129891,-0.148213,-0.181373,-0.141350,-0.174577,-0.173909,-0.172337,-0.179369,-0.160368,...,-0.174501,-0.179351,-0.159371,-0.179349,-0.144046,-0.179244,-0.179782,0.155626,1.342537,6.798017
std,0.106276,0.523092,0.166187,0.046054,0.264658,0.092584,0.065265,0.131755,0.048113,0.152200,...,0.153979,0.045502,0.126378,0.076299,0.261651,0.039592,0.054484,0.367688,1.056168,1.197351
min,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,...,-0.412327,-0.412327,-0.400985,-0.412327,-0.412327,-0.412327,-0.412327,-0.149276,-0.082072,0.526095
25%,-0.197255,-0.195386,-0.191785,-0.198843,-0.193646,-0.198433,-0.196542,-0.198402,-0.198685,-0.194221,...,-0.198514,-0.197943,-0.186394,-0.198420,-0.186367,-0.196124,-0.198130,-0.066936,0.537910,6.838092
50%,-0.171616,-0.171528,-0.164960,-0.174170,-0.166215,-0.172369,-0.170906,-0.172646,-0.173788,-0.169114,...,-0.174170,-0.173088,-0.161000,-0.173636,-0.160619,-0.171022,-0.173677,0.033753,1.059342,7.249387
75%,-0.150738,-0.151680,-0.140395,-0.156325,-0.140917,-0.151662,-0.150377,-0.152154,-0.153702,-0.146019,...,-0.155116,-0.153873,-0.144547,-0.154880,-0.143695,-0.152425,-0.154420,0.238393,1.878994,7.367030
max,3.002076,5.968738,3.438787,0.905881,6.286498,3.157411,1.462859,4.740475,0.872172,3.982874,...,5.843317,0.879330,4.146487,2.434800,7.024872,0.286806,1.615714,4.205260,5.177431,7.417178

Apply the normalisation function to the features of the test data.

In [11]:
# Apply the 'standard_scalar()' on X_test and get the descriptive statistics of the normalised X_test
norm_x_test = x_test.apply(standard_scalar,axis=1)
norm_x_test.describe()

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
count,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,...,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000,1381.000000
mean,-0.170766,-0.112679,-0.151144,-0.179056,-0.142579,-0.170781,-0.170767,-0.173596,-0.175903,-0.150910,...,-0.175507,-0.177117,-0.165559,-0.174893,-0.149666,-0.175322,-0.178346,0.139314,1.311153,6.840290
std,0.076820,0.589412,0.148475,0.048173,0.262132,0.097565,0.063308,0.057682,0.052473,0.229759,...,0.107987,0.045918,0.066995,0.163682,0.217813,0.051740,0.048552,0.391630,1.050085,1.147138
min,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,-0.412327,...,-0.412327,-0.412327,-0.340504,-0.412327,-0.412327,-0.412327,-0.412327,-0.148261,-0.126254,0.526095
25%,-0.192115,-0.190837,-0.188969,-0.195056,-0.189012,-0.193846,-0.191317,-0.193398,-0.193972,-0.189012,...,-0.194911,-0.193972,-0.184856,-0.194508,-0.181471,-0.192166,-0.194379,-0.070323,0.510770,6.893845
50%,-0.168997,-0.168322,-0.163618,-0.172150,-0.162987,-0.169634,-0.167629,-0.169901,-0.170465,-0.166417,...,-0.171738,-0.171085,-0.162089,-0.171639,-0.158131,-0.169223,-0.171217,0.014811,1.046791,7.270203
75%,-0.148754,-0.149791,-0.140357,-0.154603,-0.139452,-0.149591,-0.149867,-0.150495,-0.152113,-0.144932,...,-0.154001,-0.152337,-0.145177,-0.154036,-0.141647,-0.151487,-0.153755,0.193522,1.868159,7.372973
max,1.648120,5.968738,2.333217,0.905881,7.289508,2.178353,1.036694,0.843790,0.843855,6.507557,...,3.498154,0.577200,1.618059,5.732595,6.662495,0.745949,0.979092,4.205260,5.105993,7.417377

---

#### Activity 4: Logistic Regression - Model Training 

Implement Logistic Regression Classification using `sklearn` module to estimate the values of $\beta$ coefficients in the following way:

1. Deploy the model by importing the `LogisticRegression` class and create an object of this class.
2. Call the `fit()` function on the Logistic Regression object and print score using the `score()` function.
3. Print the $\beta$ coefficient values.

In [17]:
# Deploy the 'LogisticRegression' model using the 'fit()' function.
from sklearn.linear_model import LogisticRegression
obj = LogisticRegression()
print(obj.fit(norm_x_train,y_train))
print(obj.score(norm_x_train,y_train))

LogisticRegression()
0.8291925465838509

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Get the beta coefficients for the features using the model object trained in the above code.

In [16]:
# Print the beta coefficient values
print(obj.intercept_, obj.coef_)

[-2.63949381] [[-0.47397687 -0.4105008  -0.56652208  1.99702217  0.502085    0.49304442
   4.87975173  1.28181992  1.68370413 -0.12449316  1.46844306 -1.46085882
  -0.18846029 -0.09761178  2.13998133  2.93179149  3.14446043  0.33994574
  -0.04669192  2.27958156  0.29223712  2.28900669  3.4622465   0.77068197
  -6.12264556 -2.05101812 -4.00217051 -0.52254217 -0.76034127 -1.01194127
   0.51141405  0.79250705 -1.574812    0.80045825 -1.14699694  0.26900551
  -1.88489119 -1.04678475 -1.63768699  1.3398008  -0.13833595 -2.233808
  -0.80532975 -2.50044379 -2.53096259 -4.00187962  0.68418771 -0.43587652
   0.35398997 -1.81815491  0.09509974  0.76930193  3.31328932  1.86866134
  -2.13122477  0.67713082  0.29631265]]

----

#### Activity 5: Logistic Regression - Model Prediction and Evaluation

Predict the values for both training and test sets by calling the `predict()` function on the Logistic Regression object.

In [18]:
# Make predictions on the test dataset by using the 'predict()' function.
pred = obj.predict(x_test)

Also, display the confusion matrix.

In [21]:
# Display the results of confusion_matrix
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,pred)

array([[292, 512],
       [  3, 574]])

**Q:** What is the positive outcome out of both the labels?

**A:** 

**Q:** Write the count of True Positives and True Negatives?

**A:**


Print the classification report values to evaluate the accuracy of your model.

In [23]:
# Display the results of classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      0.36      0.53       804
           1       0.53      0.99      0.69       577

    accuracy                           0.63      1381
   macro avg       0.76      0.68      0.61      1381
weighted avg       0.80      0.63      0.60      1381

**Q** Write the f1-score of both labels?

**A:**

-----

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project77**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project77** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---